repo_id: "AlohaBusyBox" # FlipSwitch
root_dir: "" # "/mnt/shared_data/aloha_data/aloha-busybox_lerobot_v3_0/FlipSwitch/"
# batch_size: 16
num_workers: 4
use_imagenet_stats: false
prefetch_factor: 2

# Map observation keys to standard naming
observation_mapping:
  "observations.images.cam_high": "observation.image.0"
  "observations.images.cam_left_wrist": "observation.image.1"
  "observations.images.cam_right_wrist": "observation.image.2"
  "observations.joint_position": "observation.state"
  "action.joint_position": "action"
  #"observations.ee_position": "observation.state"
  #"action.ee_position": "action"

features:
  observation.image.0:
    type: VISUAL
    shape: (3,448,448)
  observation.image.1:
    type: VISUAL
    shape: (3,448,448)
  observation.image.2:
    type: VISUAL
    shape: (3,448,448)
  observation.state:
    type: STATE
    shape: (14,)
  action:
    type: ACTION
    shape: (14,)

normalization_mapping:
  VISUAL: "IDENTITY" # Keep images in [0,1] range
  STATE: "MEAN_STD" # Normalize state observations
  ACTION: "ACTIONCHUNK_MEAN_STD" # Normalize actions

# stats: !include aloha_bb_stats.json

transform_mapping:
  "action":
    - type: delta_actions
      action_type: "POSITION"
      action_key: "action"
      state_key: "observation.state"
      relative_to_state: true
      post_norm: false

  "observation.image.0":
    - type: random_resized_crop
      height: 448
      width: 448
      scale: [0.9, 0.9]
      ratio: [1.0, 1.0]

    - type: color_jitter
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      hue: 0.05

  "observation.image.1":
    - type: random_resized_crop
      height: 448
      width: 448
      scale: [0.9, 0.9]
      ratio: [1.0, 1.0]

    - type: color_jitter
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      hue: 0.05

  "observation.image.2":
    - type: random_resized_crop
      height: 448
      width: 448
      scale: [0.9, 0.9]
      ratio: [1.0, 1.0]

    - type: color_jitter
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      hue: 0.05
