repo_id: "AlohaBusyBox"
root_dir: ""
num_workers: 4
use_imagenet_stats: false
prefetch_factor: 2

observation_mapping:
  "observations.images.cam_high": "observation.image.0"
  "observations.images.cam_left_wrist": "observation.image.1"
  "observations.images.cam_right_wrist": "observation.image.2"
  "observations.ee_position_6d": "observation.state"
  "action.ee_position_6d": "action"

features:
  observation.image.0:
    type: VISUAL
    shape: (3,224,224)
  observation.image.1:
    type: VISUAL
    shape: (3,224,224)
  observation.image.2:
    type: VISUAL
    shape: (3,224,224)
  observation.state:
    type: STATE
    shape: (20,)
  action:
    type: ACTION
    shape: (20,)

normalization_mapping:
  VISUAL: IDENTITY
  STATE: MEAN_STD
  ACTION: ACTIONCHUNK_MEAN_STD

action_type: EE_6D_POS

transform_mapping:
  "observation.state":
    - type: convert_to_6d_actions
      action_key: "observation.state"
      action_type: "EE_6D_POS"
      post_norm: false

  "action":
    - type: convert_to_6d_actions
      action_key: "action"
      action_type: "EE_6D_POS"
      post_norm: false

    - type: delta_actions
      action_type: "EE_6D_POS"
      action_key: "action"
      state_key: "observation.state"
      relative_to_state: true
      post_norm: false

  "observation.image.0":
    - type: resize_with_padding
      height: 224
      width: 224

  "observation.image.1":
    - type: resize_with_padding
      height: 224
      width: 224

  "observation.image.2":
    - type: resize_with_padding
      height: 224
      width: 224
