features:
  observation.image.agentview:  # cam_scene (ZED, 360x640 native)
    type: VISUAL
    shape: (3,448,448)
  observation.image.left_wrist:  # cam_left_wrist (ZED, 360x640 native)
    type: VISUAL
    shape: (3,448,448)
  observation.image.right_wrist:  # cam_right_wrist (ZED, 360x640 native)
    type: VISUAL
    shape: (3,448,448)
  observations.joint_position:
    type: STATE
    shape: (14,)  # 2 arms x (6 joints + 1 gripper)
  observations.eef_rpy:
    type: STATE
    shape: (14,)  # 2 arms x (xyz + rpy + gripper)
  observation.state:  # eef_quat_pos
    type: STATE
    shape: (16,)  # 2 arms x (xyz + qxyzw + gripper)
  observations.velocities:
    type: STATE
    shape: (14,)
  observations.torques:
    type: STATE
    shape: (12,)
  observations.tcp_forces:
    type: STATE
    shape: (12,)
  observations.currents:
    type: STATE
    shape: (12,)
  # action.joint_position:
  #   type: ACTION
  #   shape: (14,)
  action.eef_rpy:
    type: STATE
    shape: (14,)
  action:  # eef_quat_pos
    type: ACTION
    shape: (16,)

<<: !include normalization_mapping.yaml

action_type: EE_QUAT_POS_XYZW
