"action":  # only for ACTIONCHUNK norm modes
  - type: convert_to_6d_actions
    action_key: "observation.state"
    action_type: EE_QUAT_POS_XYZW
    post_norm: False
  - type: convert_to_6d_actions
    action_key: "action"
    action_type: EE_QUAT_POS_XYZW
    post_norm: False
  - type: delta_actions
    action_key: "action"
    state_key: "observation.state"
    action_type: EE_6D_POS
    relative_to_state: true
    post_norm: False

"observation.image.agentview":  # ZED scene, 360x640 native
  - type: center_crop
    height: 360
    width: 360
  - type: resize_with_padding
    height: 448
    width: 448
  - type: random_resized_crop
    height: 448
    width: 448
    scale: [0.85, 1.0]
    ratio: [0.95, 1.05]
  - type: color_jitter
    brightness: 0.2
    contrast: [0.8, 1.2]
    saturation: [0.8, 1.2]

"observation.image.left_wrist":  # ZED wrist (left), 360x640 native
  - type: center_crop
    height: 360
    width: 360
  - type: resize_with_padding
    height: 448
    width: 448
  - type: random_resized_crop
    height: 448
    width: 448
    scale: [0.9, 1.0]
    ratio: [0.98, 1.02]
  - type: color_jitter
    brightness: 0.15
    contrast: [0.85, 1.15]
    saturation: [0.85, 1.15]

"observation.image.right_wrist":  # ZED wrist (right), 360x640 native
  - type: center_crop
    height: 360
    width: 360
  - type: resize_with_padding
    height: 448
    width: 448
  - type: random_resized_crop
    height: 448
    width: 448
    scale: [0.9, 1.0]
    ratio: [0.98, 1.02]
  - type: color_jitter
    brightness: 0.15
    contrast: [0.85, 1.15]
    saturation: [0.85, 1.15]
